---
- name: update apt
  sudo: yes
  apt: update_cache=yes cache_valid_time=3600
  
- name: install nginx
  sudo: yes
  apt: package=nginx state=present
  
- name: template over nginx.conf
  sudo: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: setup nginx host file dirs
  file: name=/etc/nginx/{{ item }} 
        state=directory 
        owner=root 
        group=root        
  sudo: yes
  with_items:
    - sites-available
    - sites-enabled

- name: open ports in firewall
  command: ufw allow {{ item }}
  sudo: yes
  with_items:
    - http
    - https

