---
- name: update apt
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: install js prereqs
  sudo: yes
  apt: pkg={{ item }}
  with_items:
    - python-software-properties
    - python
    - g++
    - make

- name: add repo
  sudo: yes
  apt_repository: repo='ppa:chris-lea/node.js'

- name: install runtime
  sudo: yes
  apt: pkg=nodejs update_cache=yes
