---
- name: update apt
  sudo: yes
  apt: update_cache=yes cache_valid_time=3600
  
- name: install imagemagick
  sudo: yes
  apt: package={{ item }} state=present
  with_items: 
    - imagemagick
    - libmagickwand-dev
